### ISSUE TITLE
Notice when self enroling in a course having no groups

### ISSUE THREAD

**Issue by matcho** [comete-upo/moodle-local-groupautoenrol#1]
Context :
Using moodle 3.0.2+
- A logged-in user is viewing a course as guest (the user is not yet enrolled in the course).
- enrol_self is enabled for this course.
- group_autoenrol seems "enabled" (the option "Groups: auto enrol" is shown in course administration menu).
- No groups are defined for this course.

Action :
The user clicks the "enrol" button.

Result :
`Notice: Trying to get property of non-object in /home/mooc/www/moodle/local/groupautoenrol/lib.php on line 9`

Suggestion :
This is the line throwing the notice :
`if (isset($groupautoenrol) && ($groupautoenrol->enable_enrol == "1")) {`
Maybe $groupautoenrol is false or something ?

Mathias

**Comment by comete-upn** [comment]
J'ai corrigé ce problème. J'ai créé un nouveau compte et 2 nouveaux dépôts :
- un pour la nouvelle version du plugin (1.1.2) comme "admin tool" pr Moodle 3.0 : https://github.com/pascal-my/moodle-admin_tool_groupautoenrol
- un pour "l'ancienne" version du plugin comme "local plugin" pour Moodle 2.x : https://github.com/pascal-my/moodle-local_groupautoenrol/tree/STABLE

Ne commentes plus sur ce dépôt mais sur le nouveau ! Merci !
