### ISSUE TITLE
table in install.xml has incorrect prefix

### ISSUE THREAD

**Issue by danmarsden** [comete-upo/moodle-local-groupautoenrol#3]
Table names should be prefixed with the full frankenstyle plugin name eg in your case "local_groupautoenrol_TABLENAME" - looks like that's the remaining issue for the travis-ci to show a "Green" build....

But... before you go and change the prefix I think you've used the wrong plugin type here - so it might be worth fixing that first. I'll create a new issue for that.

**Comment by comete-upn** [comment]
(I wrote a comment about that on the moodle plugin page)
