### ISSUE TITLE
Plugin fits better as an admin_tool plugin rather than "local"

### ISSUE THREAD

**Issue by danmarsden** [comete-upo/moodle-local-groupautoenrol#4]
There is very little difference in the available hooks/code structure between local and admin_tool plugins but your plugin appears to fit better as an Admin_tool (manipulates users/groups/courses) - the "local" plugin type is really only supposed to be used when a plugin doesn't fit the other plugin types - if you were able to convert this to an admin tool plugin (should be pretty easy and mainly involve find/replace some uses of "local" to "admin_tool") it might also make it easier for people to find your plugin within the plugins database by grouping it with similar tools.

**Comment by danmarsden** [comment]
of course - this may not block plugin approval if you don't really want to make this change - just let us know your thoughts.

**Comment by comete-upn** [comment]
(I wrote a comment about that on the moodle plugin page)
